### ISSUE TITLE
PeftModel failing to load after finetuning. Size Mismatch Error

### ISSUE THREAD

**Issue by tanmaylaud** [huggingface/peft#1328]
### System Info

I trained the phi-2 model using LoRa and deepspeed

Peft version : **0.7.1 (latest)**

Code to load model: 
```python
config = PeftConfig.from_pretrained(peft_model_name)
base_model = AutoModel.from_pretrained(config.base_model_name_or_path)
model = PeftModel.from_pretrained(base_model, peft_model_name)
```
Deepspeed config:
```
{
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "none",
            "pin_memory": true
        },
        "offload_param": {
            "device": "none",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "initial_scale_power": 10,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "bf16": {
        "enabled": "auto",
        "loss_scale": 0,
        "initial_scale_power": 10,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto",
            "torch_adam": true
        }
    },

    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto",
            "total_num_steps": "auto"
        }
    },

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 1000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```
I am getting the following error: 

```
RuntimeError: Error(s) in loading state_dict for PeftModelForFeatureExtraction:
        size mismatch for base_model.model.h.0.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.0.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.0.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.0.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.1.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.1.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.1.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.1.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.2.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.2.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.2.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.2.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.3.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.3.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.3.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.3.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.4.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.4.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.4.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.4.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.5.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.5.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.5.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.5.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.6.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.6.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.6.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.6.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.7.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.7.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.7.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.7.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.8.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.8.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.8.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.8.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.9.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.9.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.9.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.9.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.10.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.10.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.10.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.10.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.11.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.11.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.11.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.11.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.12.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.12.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.12.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.12.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.13.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.13.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.13.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.13.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.14.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.14.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.14.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.14.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.15.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.15.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.15.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.15.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.16.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.16.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.16.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.16.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.17.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.17.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.17.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.17.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.18.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.18.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.18.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.18.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.19.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.19.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.19.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.19.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.20.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.20.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.20.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.20.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.21.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.21.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.21.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.21.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.22.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.22.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.22.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.22.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.23.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.23.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.23.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.23.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.24.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.24.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.24.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.24.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.25.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.25.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.25.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.25.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.26.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.26.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.26.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.26.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.27.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.27.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.27.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.27.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.28.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.28.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.28.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.28.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.29.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.29.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.29.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.29.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.30.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.30.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.30.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.30.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
        size mismatch for base_model.model.h.31.mixer.Wqkv.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.31.mixer.Wqkv.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 16]).
        size mismatch for base_model.model.h.31.mixer.out_proj.lora_A.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([16, 2560]).
        size mismatch for base_model.model.h.31.mixer.out_proj.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([2560, 16]).
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

LoRA config during finetuning
```python
peft_config = LoraConfig(
            base_model_name_or_path=model_args.model_name_or_path,
            task_type=TaskType.FEATURE_EXTRACTION,
            r=16,
            lora_alpha=64,
            lora_dropout=0.1,
            target_modules=["Wqkv", "out_proj"],
            inference_mode=False
        )

### Expected behavior

Weights should load as expected.

**Comment by BenjaminBossan** [comment]
I think this doesn't work with Zero stage 3, but I'm not an expert. @pacman100 can tell more.

**Comment by sunxiaojie99** [comment]
@tanmaylaud Hello, have you found a solution yet

**Comment by BenjaminBossan** [comment]
@sunxiaojie99 PEFT with DeepSpeed Zero3 should now work if you follow [this DeepSpeed guide](https://huggingface.co/docs/peft/accelerate/deepspeed).

**Comment by tanmaylaud** [comment]
@BenjaminBossan I see this mentioned at the end of the guide:
```
Caveats
Merging when using PEFT and DeepSpeed is currently unsupported and will raise error.
```
So is it fixed or not fixed ?

**Comment by Mr-Lnan** [comment]
I have the same problem, have you solved it?
